name: Deep Agent Smoke Suite

on:
  schedule:
    - cron: "0 14 * * *" 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      Environment:
        description: "Which environment will be executed"
        required: true
        type: choice
        default: prod
        options: ["preprod", "staging", "stagingLatest", "prod"]
      tags:
        description: "Test tag to run (without @)"
        required: false
        type: string

jobs:
  test:
    runs-on: windows-latest
    env:
      # fallback for TEST_ENV if not set from manual dispatch
      TEST_ENV: ${{ github.event.inputs.Environment || 'prod' }}
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: "C07FJG27D2L"
      FAILURE_SLACK_CHANNEL_ID: "C07FJG27D2L"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Send initial Slack notification
        id: slack-initial
        shell: pwsh
        run: |
          npm install
          $githubActor = "${{ github.actor }}"
          $environment = "${{ env.TEST_ENV }}"
          $buildName = "Deep Agent Smoke Tests"
          $threadTs = node helpers/sendInitialSlackMessage.js "$githubActor" "$environment" "$buildName"
          echo "thread_ts=$threadTs" >> $env:GITHUB_OUTPUT
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: "C07FJG27D2L"

      - name: Debug - Environment Variables
        shell: pwsh
        run: |
          echo "Selected Environment: $env:TEST_ENV"

      - name: Install dependencies
        shell: pwsh
        run: |
          # First run npm install to generate package-lock.json if it doesn't exist
          if (-not (Test-Path -Path "package-lock.json")) {
            npm install
          } else {
            npm ci
          }
          npx playwright install --with-deps

      - name: Run all tests (no tag specified)
        if: ${{ github.event.inputs.tags == '' || github.event_name != 'workflow_dispatch' }}
        shell: pwsh
        run: |
          npx cucumber-js --tags "@smoke" --parallel 4 --format html:reports/cucumber-report.html --format json:reports/cucumber-report.json
          $exitCode = $LASTEXITCODE
          npm run report
          exit $exitCode
        env:
          CI: true
          TEST_ENV: ${{ env.TEST_ENV }}

      - name: Run tests with specific tag
        if: ${{ github.event.inputs.tags != '' && github.event_name == 'workflow_dispatch' }}
        shell: pwsh
        run: |
          npx cucumber-js --tags "@${{ github.event.inputs.tags }}" --parallel 4 --format html:reports/cucumber-report.html --format json:reports/cucumber-report.json
          $exitCode = $LASTEXITCODE
          npm run report
          exit $exitCode
        env:
          CI: true
          TEST_ENV: ${{ env.TEST_ENV }}

      - name: Generate Test Summary Report
        if: always()
        shell: pwsh
        run: |
          if (Test-Path -Path "reports/cucumber-report.json") {
            node generate-summary.js
          } else {
            Write-Host "Warning: reports/cucumber-report.json not found. Skipping summary generation."
          }

      - name: Debug - List report files
        shell: pwsh
        run: |
          Write-Host "Listing all files in reports/"
          Get-ChildItem -Recurse reports

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}-${{ env.TEST_ENV }}
          path: |
            reports/**
            cucumber-report.html
            cucumber-report.json
          retention-days: 30
          if-no-files-found: warn

      - name: Upload Playwright traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-${{ github.run_id }}-${{ env.TEST_ENV }}
          path: |
            reports/traces/
            reports/screenshots/
          retention-days: 30
          if-no-files-found: ignore
          
      - name: Send success Slack notification
        if: success()
        shell: pwsh
        run: |
          node helpers/postBuildStatus.js "success" "${{ steps.slack-initial.outputs.thread_ts }}"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: "C07FJG27D2L"
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_ACTOR: ${{ github.actor }}
          
      - name: Send failure Slack notification
        if: failure()
        shell: pwsh
        run: |
          node helpers/postBuildStatus.js "failure" "${{ steps.slack-initial.outputs.thread_ts }}"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: "C07FJG27D2L"
          FAILURE_SLACK_CHANNEL_ID: "C07FJG27D2L"
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_ACTOR: ${{ github.actor }}
